# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # To be honest, I do not care about prometheus itself for now
  # - job_name: "prometheus"
  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.
  #   static_configs:
  #     - targets: ["localhost:9090"]
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']  # the metrics exported by prometheus exporter
      - targets: ['otel-collector:8888']  # the metrics of otel-collector itself
  - job_name: "firecracker"
    scrape_interval: 1s
    file_sd_configs:
      - files:
        - /prometheus/targets/*.json
        refresh_interval: 10s
